services:
  nastuiron_hub:
    build: .
    container_name: nastuiron_hub
    restart: unless-stopped
    ports:
      - "3002:3000"
    networks:
      - nastuiron_proxy

networks:
  nastuiron_proxy:
    external: true
